name: Deploy PWA to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: pwa/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./pwa
      
      - name: Build
        run: npm run build
        working-directory: ./pwa
        env:
          VITE_API_URL: https://script.google.com/macros/s/AKfycbwFBG1nbA0pyiWfFpl5MqybR3bEYYwFJHY6GT3l6hfboU5kXnzdamJETXintswcLxI2Gw/exec
          VITE_APP_NAME: ${{ vars.APP_NAME || 'BarberBro Booking' }}
          VITE_APP_SHORT_NAME: ${{ vars.APP_SHORT_NAME || 'BarberBro' }}
          VITE_APP_DESCRIPTION: ${{ vars.APP_DESCRIPTION || 'Prenota il tuo taglio in pochi tap' }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pwa/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
